In [6]:
import numpy as np
import time
a = np.random.rand(10000000)
b = np.random.rand(10000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(c)
print("Vectorized verion:" + str(1000*(toc-tic))+"ms")

c = 0
tic = time.time()
for i in range(10000000):
    c += a[i]*b[i]
toc = time.time()

print(c)
print("for loop:"+str(1000*(toc-tic))+"ms")


2500389.2626210414
Vectorized verion:11.746644973754883ms
2500389.262621047
for loop:4835.730075836182ms


In [10]:
import numpy as np
a = np.random.randn(5)

In [11]:
print(a)

[-2.31371715 -0.80240964 -1.17396498 -1.06630866  1.98154292]


In [12]:
print(a.shape)

(5,)


In [13]:
print(a.T)

[-2.31371715 -0.80240964 -1.17396498 -1.06630866  1.98154292]


In [14]:
print(np.dot(a,a.T))

12.438868518641822


In [19]:
a = np.random.randn(5,1)
print(a)


[[ 0.79939249]
 [-0.34310888]
 [ 1.74735759]
 [-1.41473991]
 [ 0.57309503]]


In [20]:
print(a.T)

[[ 0.79939249 -0.34310888  1.74735759 -1.41473991  0.57309503]]


In [18]:
print(np.dot(a,a.T))

[[ 0.01423822 -0.13271328 -0.02181774 -0.20511061  0.09908799]
 [-0.13271328  1.23700946  0.20336136  1.911819   -0.92359094]
 [-0.02181774  0.20336136  0.03343212  0.31429842 -0.15183612]
 [-0.20511061  1.911819    0.31429842  2.95474853 -1.4274254 ]
 [ 0.09908799 -0.92359094 -0.15183612 -1.4274254   0.68958263]]


In [1]:
import numpy as np
A = np.array([[56.0,8.0,4.4,68.0],
            [1.2,104.0,52.0,8.0],
            [1.8,135.0,99.0,0.9]])
print(A)

[[ 56.    8.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [2]:
cal = A.sum(axis=0)
print(cal)

[ 59.  247.  155.4  76.9]


In [3]:
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[[94.91525424  3.2388664   2.83140283 88.42652796]
 [ 2.03389831 42.10526316 33.46203346 10.40312094]
 [ 3.05084746 54.65587045 63.70656371  1.17035111]]


In [5]:
import numpy as np
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
print(c)

[[-0.17908709 -0.88882212 -0.36562345]
 [-0.31496032 -0.25941439  0.25709505]
 [-0.27088729  0.13558027 -0.35310515]]


In [6]:
import numpy as np
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
c = a*b
print(c)

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [7]:
import numpy as np
A = np.random.randn(4,3)
B = np.sum(A, axis = 1, keepdims = True)
print(B)

[[ 1.94768237]
 [ 0.52174748]
 [ 0.13046105]
 [-1.92251092]]
